//! Typst export for layout results.

use crate::models::PageLayout;
use anyhow::{Context, Result};
use chrono::Datelike;
use std::path::{Path, PathBuf};
use typst::LibraryExt;
use typst::foundations::Bytes;
use typst::utils::LazyHash;
use typst_kit::fonts::{FontSlot, Fonts};

/// Exports a layout result to a Typst file.
///
/// The generated `.typ` file contains `#place(...)` commands for each photo.
pub fn export_typst(layout: &PageLayout, photo_paths: &[String], output_path: &Path) -> Result<()> {
    let typst_source = generate_typst_source(layout, photo_paths);

    std::fs::write(output_path, typst_source)
        .with_context(|| format!("Failed to write Typst file to {:?}", output_path))?;

    Ok(())
}

/// Exports a layout result to a PDF file by compiling via Typst.
pub fn export_pdf(
    layout: &PageLayout,
    photo_paths: &[String],
    base_dir: &Path,
    output_path: &Path,
) -> Result<()> {
    // Convert photo paths to be relative to base_dir for Typst resolution
    let relative_paths: Vec<String> = photo_paths
        .iter()
        .map(|p| {
            let path = Path::new(p);
            path.strip_prefix(base_dir)
                .ok()
                .and_then(|rel| rel.to_str())
                .map(|s| s.to_string())
                .unwrap_or_else(|| p.clone())
        })
        .collect();

    let typst_source = generate_typst_source(layout, &relative_paths);
    let pdf_bytes = compile_to_pdf(&typst_source, base_dir)?;
    write_pdf(&pdf_bytes, output_path)?;
    Ok(())
}

/// Generates Typst source code for a layout.
fn generate_typst_source(layout: &PageLayout, photo_paths: &[String]) -> String {
    let mut out = String::new();

    // Page setup
    out.push_str(&format!(
        "// Generated by photobook-solver\n\
         #set page(width: {w}mm, height: {h}mm, margin: 0pt)\n\n",
        w = layout.canvas.width,
        h = layout.canvas.height,
    ));

    // Place each photo
    for placement in &layout.placements {
        let path = photo_paths
            .get(placement.photo_idx as usize)
            .map(|s| s.as_str())
            .unwrap_or("unknown.jpg");

        out.push_str(&format!(
            "#place(top + left, dx: {x:.2}mm, dy: {y:.2}mm, \
             block(width: {w:.2}mm, height: {h:.2}mm, clip: true, \
             image(\"{path}\", width: {w:.2}mm, height: {h:.2}mm, fit: \"cover\")))\n",
            x = placement.x,
            y = placement.y,
            w = placement.w,
            h = placement.h,
        ));
    }

    out
}

/// Compiles a Typst source string directly to a PDF byte vector.
///
/// `base_dir` is used to resolve relative image paths in the source.
fn compile_to_pdf(source: &str, base_dir: &Path) -> Result<Vec<u8>> {
    let fonts = Fonts::searcher().search();
    let world = PhotobookWorld::new(source.to_string(), base_dir.to_path_buf(), fonts);

    let result = typst::compile(&world);

    // Collect and print warnings.
    for warning in &result.warnings {
        tracing::warn!("Typst: {}", warning.message);
    }

    let document = result.output.map_err(|errors| {
        let messages: Vec<String> = errors
            .iter()
            .map(|e| format!("{:?}: {}", e.span.id(), e.message))
            .collect();
        anyhow::anyhow!("Typst compilation failed:\n{}", messages.join("\n"))
    })?;

    let pdf_bytes = typst_pdf::pdf(&document, &typst_pdf::PdfOptions::default())
        .map_err(|e| anyhow::anyhow!("PDF export failed: {:?}", e))?;

    Ok(pdf_bytes)
}

/// Writes compiled PDF bytes to a file.
fn write_pdf(bytes: &[u8], output_path: &Path) -> Result<()> {
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Cannot create output directory for {:?}", output_path))?;
    }
    std::fs::write(output_path, bytes)
        .with_context(|| format!("Cannot write PDF to {:?}", output_path))
}

// ── Typst World implementation ────────────────────────────────────────────────

/// Minimal `typst::World` implementation for photobook generation.
struct PhotobookWorld {
    source: typst::syntax::Source,
    base_dir: PathBuf,
    library: LazyHash<typst::Library>,
    book: LazyHash<typst::text::FontBook>,
    fonts: Vec<FontSlot>,
    timestamp: chrono::DateTime<chrono::Utc>,
}

impl PhotobookWorld {
    fn new(source: String, base_dir: PathBuf, fonts: Fonts) -> Self {
        let source = typst::syntax::Source::new(
            typst::syntax::FileId::new(None, typst::syntax::VirtualPath::new("main.typ")),
            source,
        );

        Self {
            source,
            base_dir,
            library: LazyHash::new(typst::Library::default()),
            book: LazyHash::new(fonts.book),
            fonts: fonts.fonts,
            timestamp: chrono::Utc::now(),
        }
    }
}

impl typst::World for PhotobookWorld {
    fn library(&self) -> &LazyHash<typst::Library> {
        &self.library
    }

    fn book(&self) -> &LazyHash<typst::text::FontBook> {
        &self.book
    }

    fn main(&self) -> typst::syntax::FileId {
        self.source.id()
    }

    fn source(&self, id: typst::syntax::FileId) -> typst::diag::FileResult<typst::syntax::Source> {
        if id == self.source.id() {
            Ok(self.source.clone())
        } else {
            Err(typst::diag::FileError::NotFound(
                id.vpath().as_rootless_path().to_path_buf(),
            ))
        }
    }

    fn file(&self, id: typst::syntax::FileId) -> typst::diag::FileResult<Bytes> {
        let abs_path = self.base_dir.join(id.vpath().as_rootless_path());

        std::fs::read(&abs_path)
            .map(Bytes::new)
            .map_err(|_| typst::diag::FileError::NotFound(abs_path))
    }

    fn font(&self, index: usize) -> Option<typst::text::Font> {
        self.fonts.get(index).and_then(|slot| slot.get())
    }

    fn today(&self, offset: Option<i64>) -> Option<typst::foundations::Datetime> {
        let adjusted = match offset {
            None => self.timestamp,
            Some(h) => self.timestamp + chrono::Duration::hours(h),
        };

        typst::foundations::Datetime::from_ymd(
            adjusted.year(),
            adjusted.month() as u8,
            adjusted.day() as u8,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{Canvas, PhotoPlacement};

    #[test]
    fn test_generate_typst_source() {
        let canvas = Canvas::new(1000.0, 800.0, 5.0, 0.0);
        let placements = vec![
            PhotoPlacement {
                photo_idx: 0,
                x: 10.0,
                y: 20.0,
                w: 300.0,
                h: 200.0,
            },
            PhotoPlacement {
                photo_idx: 1,
                x: 320.0,
                y: 20.0,
                w: 400.0,
                h: 200.0,
            },
        ];

        let layout = PageLayout::new(placements, canvas);
        let photo_paths = vec!["photo1.jpg".to_string(), "photo2.jpg".to_string()];

        let source = generate_typst_source(&layout, &photo_paths);

        assert!(source.contains("#set page"));
        assert!(source.contains("photo1.jpg"));
        assert!(source.contains("photo2.jpg"));
        assert!(source.contains("#place"));
    }
}
