use anyhow::{Context, Result};
use chrono::Datelike;
use std::path::{Path, PathBuf};
use typst::LibraryExt;
use typst::foundations::Bytes;
use typst::utils::LazyHash;
use typst_kit::fonts::{FontSlot, Fonts};

use crate::models::{BookConfig, Page, Placement};

// ── .typ source generation ────────────────────────────────────────────────────

/// Generates a complete Typst source document from the solved page layout.
///
/// `base_dir` is emitted as `img-root` at the top of the document so image
/// paths appear as `img-root + "/group/photo.jpg"` instead of repeating the
/// full root path on every `#place` call.
pub fn generate_typ(pages: &[Page], config: &BookConfig, base_dir: &Path) -> String {
    let mut out = String::new();

    let root = base_dir.to_string_lossy().replace('\\', "/");
    out.push_str(&format!(
        "// Generated by photobook-solver\n\
         // Image root: {root}\n\
         // To compile standalone: typst compile <this-file> --root {root}\n\n"
    ));

    // Page setup: no margins (we handle them ourselves via place()).
    out.push_str(&format!(
        "#set page(width: {w}mm, height: {h}mm, margin: 0pt)\n\n",
        w = config.page_width_mm,
        h = config.page_height_mm,
    ));

    for (i, page) in pages.iter().enumerate() {
        if i > 0 {
            out.push_str("#pagebreak()\n");
        }
        out.push_str(&render_page(page, base_dir));
    }

    out
}

/// Renders a single page as a Typst block of `#place(...)` calls.
fn render_page(page: &Page, base_dir: &Path) -> String {
    let mut out = String::new();

    for placement in &page.placements {
        out.push_str(&render_placement(placement, base_dir));
    }

    out
}

/// Renders a single image placement as a Typst `#place(...)` call.
///
/// Paths are relative to `base_dir` so Typst can resolve them via the World.
/// Falls back to the absolute path if the photo is outside `base_dir`.
fn render_placement(p: &Placement, base_dir: &Path) -> String {
    // Use root-relative paths ("group/photo.jpg") so the .typ file works both
    // via our World implementation and via `typst compile --root <base_dir>`.
    let path = match p.photo.path.strip_prefix(base_dir) {
        Ok(rel) => format!("{}", rel.to_string_lossy().replace('\\', "/")),
        Err(_) => p.photo.path.to_string_lossy().replace('\\', "/"),
    };

    format!(
        "#place(top + left, dx: {x:.2}mm, dy: {y:.2}mm, \
         block(width: {w:.2}mm, height: {h:.2}mm, clip: true, \
         image(\"{path}\", width: {w:.2}mm, height: {h:.2}mm, fit: \"cover\")))\n",
        x = p.x_mm,
        y = p.y_mm,
        w = p.width_mm,
        h = p.height_mm,
    )
}

/// Writes the Typst source to a `.typ` file.
pub fn write_typ_file(source: &str, output_path: &Path) -> Result<()> {
    create_output_dir(output_path)?;
    std::fs::write(output_path, source)
        .with_context(|| format!("Cannot write .typ file to {:?}", output_path))
}

fn create_output_dir(output_path: &Path) -> Result<(), anyhow::Error> {
    let parent = output_path
        .parent()
        .ok_or_else(|| anyhow::anyhow!("Output path {} has no parent", output_path.display()))?;
    std::fs::create_dir_all(parent)
        .with_context(|| format!("Cannot create output directory for {:?}", output_path))?;
    Ok(())
}

// ── PDF compilation ───────────────────────────────────────────────────────────

/// Compiles a Typst source string directly to a PDF byte vector.
///
/// `base_dir` is used to resolve relative image paths in the source.
pub fn compile_to_pdf(source: &str, base_dir: &Path) -> Result<Vec<u8>> {
    let fonts = Fonts::searcher().search();

    let world = PhotobookWorld::new(source.to_string(), base_dir.to_path_buf(), fonts);

    let result = typst::compile(&world);

    // Collect and print warnings.
    for warning in &result.warnings {
        tracing::warn!("Typst: {}", warning.message);
    }

    let document = result.output.map_err(|errors| {
        let messages: Vec<String> = errors
            .iter()
            .map(|e| format!("{:?}: {}", e.span.id(), e.message))
            .collect();
        anyhow::anyhow!("Typst compilation failed:\n{}", messages.join("\n"))
    })?;

    let pdf_bytes = typst_pdf::pdf(&document, &typst_pdf::PdfOptions::default())
        .map_err(|e| anyhow::anyhow!("PDF export failed: {:?}", e))?;

    Ok(pdf_bytes)
}

/// Writes compiled PDF bytes to a file.
pub fn write_pdf(bytes: &[u8], output_path: &Path) -> Result<()> {
    create_output_dir(output_path)?;
    std::fs::write(output_path, bytes)
        .with_context(|| format!("Cannot write PDF to {:?}", output_path))
}

// ── Typst World implementation ────────────────────────────────────────────────

/// Minimal `typst::World` implementation for photobook generation.
///
/// - The main source is held in memory as a string.
/// - All file access (images) is resolved relative to `base_dir`.
/// - Fonts are loaded from the system via `typst-kit`.
struct PhotobookWorld {
    source: typst::syntax::Source,
    base_dir: PathBuf,
    library: LazyHash<typst::Library>,
    book: LazyHash<typst::text::FontBook>,
    fonts: Vec<FontSlot>,
    /// Timestamp used for reproducible builds.
    timestamp: chrono::DateTime<chrono::Utc>,
}

impl PhotobookWorld {
    fn new(source: String, base_dir: PathBuf, fonts: Fonts) -> Self {
        let source = typst::syntax::Source::new(
            typst::syntax::FileId::new(None, typst::syntax::VirtualPath::new("main.typ")),
            source,
        );

        Self {
            source,
            base_dir,
            library: LazyHash::new(typst::Library::default()),
            book: LazyHash::new(fonts.book),
            fonts: fonts.fonts,
            timestamp: chrono::Utc::now(),
        }
    }
}

impl typst::World for PhotobookWorld {
    fn library(&self) -> &LazyHash<typst::Library> {
        &self.library
    }

    fn book(&self) -> &LazyHash<typst::text::FontBook> {
        &self.book
    }

    fn main(&self) -> typst::syntax::FileId {
        self.source.id()
    }

    fn source(&self, id: typst::syntax::FileId) -> typst::diag::FileResult<typst::syntax::Source> {
        if id == self.source.id() {
            Ok(self.source.clone())
        } else {
            Err(typst::diag::FileError::NotFound(
                id.vpath().as_rootless_path().to_path_buf(),
            ))
        }
    }

    fn file(&self, id: typst::syntax::FileId) -> typst::diag::FileResult<Bytes> {
        let abs_path = self.base_dir.join(id.vpath().as_rootless_path());

        std::fs::read(&abs_path)
            .map(Bytes::new)
            .map_err(|_| typst::diag::FileError::NotFound(abs_path))
    }

    fn font(&self, index: usize) -> Option<typst::text::Font> {
        self.fonts.get(index).and_then(|slot| slot.get())
    }

    fn today(&self, offset: Option<i64>) -> Option<typst::foundations::Datetime> {
        let adjusted = match offset {
            None => self.timestamp,
            Some(h) => self.timestamp + chrono::Duration::hours(h),
        };

        typst::foundations::Datetime::from_ymd(
            adjusted.year(),
            adjusted.month() as u8,
            adjusted.day() as u8,
        )
    }
}
